### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by bubnenkoff** [kunaljainwin/Flutter#1]
It would be nice to have placeholder support.

**Comment by kunaljainwin** [comment]
Hi , i am author of this repo can you elaborate what do you mean by placeholder in reference to my text_chip_field package ,Your feedback means a lot

**Comment by bubnenkoff** [comment]
@kunaljainwin I mean something like this:
![изображение](https://user-images.githubusercontent.com/6514326/174976676-43327294-f3ee-490b-9351-f88cac331953.png)

**Comment by kunaljainwin** [comment]
yes, the package has this feature refer to this code` TextChipField(
                  initialString: ctrl.purchaseNumbers,
                  seprator: " ",
                  decoration: InputDecoration(
                    hintText:"First Name",
                  
                  ),
                  onChanged: (val) {
                    ctrl.purchaseNumbers = val;
                    print('data: ${ctrl.purchaseNumbers}');
                  },
                ),`

**Comment by bubnenkoff** [comment]
I mean some text that displays on empty input. Like html input
placeholders.

Сб, 18 июня 2022 г. в 09:11, Kunal jain ***@***.***>:
